export const LOADING_FORMATION="LOADING_FORMATION";
export const GET_ALL_FORMATION_SUCCESS = "GET_ALL_FORMATION_SUCCESS";
export const GET_ALL_FORMATION_FAIL = "GET_ALL_FORMATION_FAIL";


export const ADD_FORMATION_SUCCESS = "ADD_FORMATION_SUCCESS";
export const ADD_FORMATION_FAIL = "ADD_FORMATION_FAIL";


export const DELETE_FORMATION_SUCCESS = "DELETE_FORMATION_SUCCESS";
export const DELETE_FORMATION_FAIL = "DELETE_FORMATION_FAIL";

export const GET_ONE_FORMATION_SUCCESS = "GET_ONE_FORMATION_SUCCESS";
export const GET_ONE_FORMATION_FAIL = "GET_ONE_FORMATION_FAIL";

export const UPDATE_FORMATION_SUCCESS = "UPDATE_FORMATION_SUCCESS";
export const UPDATE_FORMATION_FAIL = "UPDATE_FORMATION_FAIL";