export const LOADING_PROFILE="LOADING_PROFILE";
export const SAVE_PROFILE_SUCCESS="SAVE_PROFILE_SUCCESS";
export const SAVE_PROFILE_FAIL="SAVE_PROFILE_FAIL";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_ONE_PROFILE_FAIL";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";